### PR TITLE
Fix broken files module link

### PR DESCRIPTION
**Pull request by mattcdavis1**
Fix broken files module link

### CODE REVIEW

**Comment by RyanThompson** [comment]
This should not be needed as it's inherent. Are you up to date or do you have any overrides occurring in the files module for anything?

**Comment by mattcdavis1** [comment]
i am not on the latest version but can you confirm that the "View" link in the `admin/files` listing table works for you?  If so then i'll just assume it's either resolved in a later version or related to an override of some sort.  It definitely was not working for us.

https://goo.gl/ir1L96

**Comment by RyanThompson** [comment]
Working like a charm. Let me know what you find out.

**Comment by RyanThompson** [comment]
PS the default behavior is `{current_path}/{button_slug}/{entry_id}` if not explicitly defined otherwise.

**Pull request closed without merging**
